sudo: required
services:
  - docker

before_install:
  - docker build -t simonflueeliti8m/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true simonflueeliti8m/react-test npm test

after_success:
  - docker build -t simonflueeliti8m/multi-client ./client
  - docker build -t simonflueeliti8m/multi-nginx ./nginx
  - docker build -t simonflueeliti8m/multi-server ./server
  - docker build -t simonflueeliti8m/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push it to docker hub
  - docker push simonflueeliti8m/multi-client
  - docker push simonflueeliti8m/multi-nginx
  - docker push simonflueeliti8m/multi-server
  - docker push simonflueeliti8m/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: MY_REGION
  app: MY_APP_NAME
  env: MY_ENV
  bucket_name: MY_BUCKET_NAME
  bucket_path: MY_BUCKET_PATH
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
